name: teranga_agro
description: Une plateforme de digitalisation agricole combinant un ERP agricole et une marketplace pour moderniser le secteur agroalimentaire sénégalais.

publish_to: 'none' # Ne pas publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^15.0.0
  http: ^1.2.2
  flutter_iconly: ^1.0.2
  flutter_tts: ^4.0.2
  dartz: ^0.10.1

  # UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  fl_chart: ^0.71.0

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  get_it: ^8.0.3

  # Networking
  dio: ^5.3.2
  connectivity_plus: ^6.1.3
  
  # Storage
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  
  # Location services
  geolocator: ^14.0.0
  google_maps_flutter: ^2.5.0
  
  # Utils
  intl: ^0.19.0
  image_picker: ^1.0.4
  permission_handler: ^12.0.0+1
  url_launcher: ^6.1.14
  path_provider: ^2.1.1
  logger: ^2.0.2
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  generate: true  # Active la génération automatique pour les localisations

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/TerangaAgro_2.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/TerangaAgro_2.jpeg"

flutter_localizations:
  enabled: true

arb-dir: lib/l10n
template-arb-file: app_fr.arb
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: lib/l10n/untranslated_wo.txt
